services:
  web-client:
    build:
      context: ./web-client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - identity-service

  identity-service:
    build:
      context: ./identity-service
      dockerfile: Dockerfile
    expose:
      - "8080"
